
-- DROP the tables and constraints
DROP TABLE IF EXISTS stock;
DROP TABLE IF EXISTS strategy;
DROP TABLE IF EXISTS user;

CREATE TABLE strategy (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    stocks INTEGER[],
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- create the project table, it depends on no other
CREATE TABLE stock (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ticker TEXT NOT NULL,
    industry TEXT NOT NULL,
    shares INTEGER not null,
    price NUMERIC not null,
    EPS1 NUMERIC NOT NULL,
    EPS5 NUMERIC NOT NULL,
    yield NUMERIC NOT NULL,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);

